Fixed a few tex-o's...
j2kun/restrepo-1957 pull request #1
Opened 2018-12-03 20:48 UTC by jj5

Hi there. A few small fixes and improvements...

2018-12-03 21:44 UTC, j2kun requested changes
Wow! I had no idea anyone was paying attention to this repo (and I still have to work through the paper myself for a sanity check).

I will eventually post this on the arXiv, so if you'd like I can include your name as a thanks at the end.

2018-12-03 21:44 UTC, j2kun commented on main.tex
> +$\mathbf{Normalizing Equations}$
```suggestion
\textbf{Normalizing Equations}
```

2018-12-03 21:44 UTC, j2kun commented on main.tex
> +$\mathbf{Equations from Lemma~\ref{lemma:coefficient-equations} and
```suggestion
\textbf{Equations from Lemma~\ref{lemma:coefficient-equations} and
```

2018-12-03 21:44 UTC, j2kun commented on main.tex
> +Lemma~\ref{lemma:optimality-of-corresponding-strategies}}$
```suggestion
Lemma~\ref{lemma:optimality-of-corresponding-strategies}}
```

2018-12-03 21:44 UTC, j2kun commented on main.tex
> +$\mathbf{Normalizing Equations}$
Good catch! Note that `\textbf` is the canonical way to make paragraph text bold, so please include my little patch :)

2018-12-03 21:59 UTC, jj5 commented
I'm happy for you to leave my name off. I'm still new to github so please bear with me as I figure out how pull requests work... :P

2018-12-03 22:03 UTC, jj5 commented
Oh. I closed the pull request. But I don't think I was supposed to do that. So now I've reopened the pull request... help? :P

2018-12-04 00:21 UTC, j2kun approved these changes

2018-12-04 00:22 UTC, merged

2018-12-04 00:22 UTC, j2kun commented
Looks good to me! Merging, and thanks again!